# Trigger Build Final v6 - Optimized Structural Sync
name: CarteNabil-Android-Build-APK-Final

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Generate Launcher Icons
        run: flutter pub run flutter_launcher_icons

      - name: Generate Release Keystore
        run: |
          keytool -genkey -v -keystore android/app/release.jks -alias carte_nabil -keyalg RSA -keysize 2048 -validity 10000 -storepass "password123" -keypass "password123" -dname "CN=USMA, OU=Zone14, O=ELASSIMA, L=Alger, S=Alger, C=DZ"

      - name: Build APK Release
        env:
          KEYSTORE_PATH: "release.jks"
          KEYSTORE_PASSWORD: "password123"
          KEY_ALIAS: "carte_nabil"
          KEY_PASSWORD: "password123"
        run: flutter build apk --release --target-platform android-arm64

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ASSIMA-10-Final-APK
          path: build/app/outputs/flutter-apk/app-release.apk
